version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: facebookdb
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgres/data
volumes:
  pgdata: