### Create User
POST http://localhost:4000/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "vaniko@gmail.com",
  "password": "vano1234",
  "firstname": "Vaniko",
  "username": "vano.akofa11"
}

### Login
POST http://localhost:4000/api/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "vanikoakofa@gmail.com",
  "password": "vano1234"
}

### Current User
GET http://localhost:4000/api/users/currentuser
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJndmFudHNhMTEyQGdtYWlsLmNvbSIsImlhdCI6MTY0MTA2NzAxOH0.F1qsyu9BxAsExAL6P7seaBu7ngVfPILUPRfRGCFrrO8

### FIND TEST
POST http://localhost:4000/api/users/find HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY0MDg4ODY1NH0.K0f0UMd0Lt4Q3QfPanIqXById4Iu82wDIewtaPo99RA

{
  "email": "test@gmail.com;DROP TABLE posts;"
}


### ADD FRIEND
POST http://localhost:4000/api/users/addfriend HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ2YW5pa29ha29mYUBnbWFpbC5jb20iLCJpYXQiOjE2NDA5NzU4OTN9.W_JZMzkXn3OkWcG1moHoDCfOCvi6MuboKwMNiVVVnAI

{
  "friendId": 4
}